// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUGmRoLgIaJg8KFs2AF81oqpeK82w-LLI',
    appId: '1:57158223229:web:62728b3c7a40f230923814',
    messagingSenderId: '57158223229',
    projectId: 'chat-app-21a02',
    authDomain: 'chat-app-21a02.firebaseapp.com',
    storageBucket: 'chat-app-21a02.appspot.com',
    measurementId: 'G-XCHHYBFGXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmgAtZFmArJ1QNv5Rs0YCzNiFsIuQsrlI',
    appId: '1:57158223229:android:924b3395add31ab0923814',
    messagingSenderId: '57158223229',
    projectId: 'chat-app-21a02',
    storageBucket: 'chat-app-21a02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN54L5O6imYc9rUw2Vw9IpWgh3Q_kQeFk',
    appId: '1:57158223229:ios:10e858a9a3040859923814',
    messagingSenderId: '57158223229',
    projectId: 'chat-app-21a02',
    storageBucket: 'chat-app-21a02.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN54L5O6imYc9rUw2Vw9IpWgh3Q_kQeFk',
    appId: '1:57158223229:ios:10e858a9a3040859923814',
    messagingSenderId: '57158223229',
    projectId: 'chat-app-21a02',
    storageBucket: 'chat-app-21a02.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUGmRoLgIaJg8KFs2AF81oqpeK82w-LLI',
    appId: '1:57158223229:web:eb50fc906abcfec4923814',
    messagingSenderId: '57158223229',
    projectId: 'chat-app-21a02',
    authDomain: 'chat-app-21a02.firebaseapp.com',
    storageBucket: 'chat-app-21a02.appspot.com',
    measurementId: 'G-Z3VQN5SLHD',
  );

}